### ISSUE TITLE
How to train another game

### ISSUE THREAD

**Issue by gwc2017180303** [Mawiszus/TOAD-GAN#1]
I want to train another game. What should I do and how to prepare the data? Thank you

**Comment by Mawiszus** [comment]
I suggest adding your game as a new option to the _--game_ command in **config.py**, and adding a new folder with the necessary code just like for Mario and Mariokart. Here's how you would do that:

For the method to be adapted to a new game, it needs a new token hierarchy. This hierarchy is defined in the **tokens.py** file, where the ascii characters that represent the sprites are assigned groups and then these groups are ordered. If you compare the tokens.py file for mario with table 1 from the paper, you can see how they correspond.
The text file you train with should then use the ascii characters defined in this file.

Usually, the method will also use a **level_image_gen.py** to generate image files directly from the ascii text files. This was implemented as it was difficult to interpret the text files directly and just nicer to look at. You could write your own renderer similar to the level_image_gen.py for Mario and Mariokart or maybe even use an external renderer here. Or you could just find all the calls of "opt.ImgGen" and comment out the code related to image generation and saving and just use the text representations until after training.

The **special_mario_downsampling.py** and **special_mariokart_downsampling.py** define how the downsampling handles the token hierarchy and, since they are the same in the end anyway, can probably just be copied over for any new game. If there is something that needs to be handled in a special way during the downsampling it would be changed here.

If you have these three things (tokens.py, level_image_gen.py and special_*_downsampling.py) and add your game specific options to anywhere "opt.game" is referenced in the code, you should be able to use your own game with the method.

I should probably add this explanation to the Readme.md later. 😄

**Comment by gwc2017180303** [comment]
> I suggest adding your game as a new option to the _--game_ command in **config.py**, and adding a new folder with the necessary code just like for Mario and Mariokart. Here's how you would do that:
> 
> For the method to be adapted to a new game, it needs a new token hierarchy. This hierarchy is defined in the **tokens.py** file, where the ascii characters that represent the sprites are assigned groups and then these groups are ordered. If you compare the tokens.py file for mario with table 1 from the paper, you can see how they correspond.
> The text file you train with should then use the ascii characters defined in this file.
> 
> Usually, the method will also use a **level_image_gen.py** to generate image files directly from the ascii text files. This was implemented as it was difficult to interpret the text files directly and just nicer to look at. You could write your own renderer similar to the level_image_gen.py for Mario and Mariokart or maybe even use an external renderer here. Or you could just find all the calls of "opt.ImgGen" and comment out the code related to image generation and saving and just use the text representations until after training.
> 
> The **special_mario_downsampling.py** and **special_mariokart_downsampling.py** define how the downsampling handles the token hierarchy and, since they are the same in the end anyway, can probably just be copied over for any new game. If there is something that needs to be handled in a special way during the downsampling it would be changed here.
> 
> If you have these three things (tokens.py, level_image_gen.py and special_*_downsampling.py) and add your game specific options to anywhere "opt.game" is referenced in the code, you should be able to use your own game with the method.
> 
> I should probably add this explanation to the Readme.md later. smile



Thank you for your detailed answer. Now I have a question during my training. Why do I use 4 RGBA images and how to make your RGBA images? My RGBA images have some problems.

**Comment by Mawiszus** [comment]
I'm sorry but I don't think I understand your question. 
Are you trying to use RGBA images as input for the method? That will not work, it expects a .txt file representing the tokens/tiles of the level. Please compare to the input .txt files in the input folder for Mario and Mariokart.
If this was not your question, could you reframe it?

**Comment by gewenchao** [comment]
> I'm sorry but I don't think I understand your question.
> Are you trying to use RGBA images as input for the method? That will not work, it expects a .txt file representing the tokens/tiles of the level. Please compare to the input .txt files in the input folder for Mario and Mariokart.
> If this was not your question, could you reframe it?
Hi,here is part of the code,  I don't know why  use four RGBA images here.  Do I need to make RGBA images to train and how to make RGBA images like you?
class LevelImageGen:
    """ Generates PIL Image files from Super Mario Bros. ascii levels.
    Initialize once and then use LevelImageGen.render() to generate images. """
    def __init__(self, sprite_path):
        """ sprite_path: path to the folder of sprite files, e.g. 'mario/sprites/' """

        # Load Graphics (assumes sprite_path points to "img" folder of Mario-AI-Framework or provided sprites folder
        mariosheet = Image.open(os.path.join(sprite_path, 'smallmariosheet.png'))
        enemysheet = Image.open(os.path.join(sprite_path, 'enemysheet.png'))
        itemsheet = Image.open(os.path.join(sprite_path, 'itemsheet.png'))
        mapsheet = Image.open(os.path.join(sprite_path, 'mapsheet.png'))

**Comment by gwc2017180303** [comment]
> I'm sorry but I don't think I understand your question.
> Are you trying to use RGBA images as input for the method? That will not work, it expects a .txt file representing the tokens/tiles of the level. Please compare to the input .txt files in the input folder for Mario and Mariokart.
> If this was not your question, could you reframe it?


Hi,here is part of the code, I don't know why use four RGBA images here. Do I need to make RGBA images to train and how to make RGBA images like you?


class LevelImageGen:
    """ Generates PIL Image files from Super Mario Bros. ascii levels.
    Initialize once and then use LevelImageGen.render() to generate images. """
    def __init__(self, sprite_path):
        """ sprite_path: path to the folder of sprite files, e.g. 'mario/sprites/' """
        # Load Graphics (assumes sprite_path points to "img" folder of Mario-AI-Framework or provided sprites folder
        mariosheet = Image.open(os.path.join(sprite_path, 'smallmariosheet.png'))
        enemysheet = Image.open(os.path.join(sprite_path, 'enemysheet.png'))
        itemsheet = Image.open(os.path.join(sprite_path, 'itemsheet.png'))
        mapsheet = Image.open(os.path.join(sprite_path, 'mapsheet.png'))

**Comment by Mawiszus** [comment]
Oh, you're trying to write a new **level_image_gen**. 
So, this code is just how we ended up rendering mario images, since these were the spritesheets we had available for the game. How you implement the level renderer for your game is entirely up to you. If you only have one spritesheet containing your sprites, of course you only need to load one. 
The `mariokart/level_image_gen.py` is probably a better fit to base your code on, it's simpler and also only uses one spritesheet.
